site_name: JONATHAN
theme: flatly

nav: 
  - Home: 'index.md'
  - BLAZE: 'blaze01.md'
  - MySQL: 'mysql.md'
  - MongoDB: 'mongoDB.md'
  - PythonDados: 'pythonDados.md'
  - RESUMOS:
    - NodeJS: 'RESUMOS/nodeJS.md'
    - Ruby: 'RESUMOS/ruby.md'
    - CSS: 'RESUMOS/css.md'

extra_css:
  - css/extra_css.css
