site_name: JONATHAN
theme: flatly

nav: 
  - BLAZE: 
    - Blaze - Instalações: 'BLAZE/blaze01.md'
    - Blaze - Utilização: 'BLAZE/blaze02.md'
    - Blaze - Deploy: 'BLAZE/blaze03.md'
    
  - DMPS:
    - TUTORIAL 01: 'DMPS/dmps01.md'
    
  - DATA-SCIENCE:
    - PythonDados: 'DATA-SCIENCE/pythonDados.md'
    - Web Screping: 'DATA-SCIENCE/pyScrap4.md'
    - Perceptron: 'DATA-SCIENCE/perceptron.md'
    
  - DATABASES:
    - MySQL: 'DATABASES/mysql.md'
    - MongoDB: 'DATABASES/mongoDB.md'
    
  - RESUMOS:
    - NodeJS: 'RESUMOS/nodeJS.md'
    - Ruby: 'RESUMOS/ruby.md'
    - CSS: 'RESUMOS/css.md'

extra_css:
  - css/extra_css.css
